创建节点:
  createElement()
  createTextNode()
  createAttribute()
  createComment()
插入节点:
  appendChild()
  insertBefore()
删除节点:
  removeChild()
查找节点:
  getElementById()
  getElementByTagName()
  getElementByName()
  querySeletor()
替换节点:
  relpaceChild()