WebRTC代表“Web实时通信”。这基本上允许在浏览器中进行语音、视频聊天和P2P共享（实时通信）
实际应用的要求来源https://www.zhihu.com/question/25497090/answer/43395462
用WebRTC来做视频直播
一个实现了WebRTC相关协议的客户端。比如Chrome浏览器
架设一个类似MCU系统的服务器
第一步，直播的客户端，比如Chrome浏览器，通过WebRTC相关的媒体API获取图像及声音信源，再用WebRTC中的通信API将图像和声音数据发送到MCU服务器。
第二步，MCU服务器根据需求对图像和声音数据进行必要的处理，比如压缩、混音等。
第三步，需要看直播的用户，通过他们的Chrome浏览器，链接上MCU服务器，并收取服务器转发来的图像和声音流。
入门https://zhuanlan.zhihu.com/p/59520779